name: analytic_engineer_exercise
version: 1.0.0
config-version: 2

profile: default

quoting:
  database: false
  schema: false
  identifier: false

target-path: target
clean-targets:
  - target
  - dbt_modules

model-paths:
  - models
macro-paths:
  - macros
seed-paths:
  - seeds
test-paths:
  - tests
snapshot-paths:
  - snapshots
analysis-paths:
  - analyses

models:
  analytic_engineer_exercise:
    staging:
      +materialized: view
    mart:
      +materialized: table

seeds:
  analytic_engineer_exercise:
    +quote_columns: false