name: analytic_engineer_solution
version: 1.0.0
config-version: 2

profile: analytic_engineer_solution

target-path: target
clean-targets:
  - target
  - dbt_packages

model-paths:
  - models
macro-paths:
  - macros
seed-paths:
  - seeds
test-paths:
  - tests
snapshot-paths:
  - snapshots
analysis-paths:
  - analyses

models:
  analytic_engineer_solution:
    staging:
      +materialized: view
    mart:
      +materialized: table

seeds:
  analytic_engineer_solution:
    +schema: raw
    +quote_columns: false
